name:build-cv

on:
push:
paths:
-"cv/**"
-".github/workflows/cv.yml"
workflow_dispatch:

permissions:
contents:write

jobs:
build:
runs-on:ubuntu-latest
steps:
-name:Checkout
uses:actions/checkout@v4

-name:CompileLaTeXtoPDF(pdflatexvialatexmk)
uses:xu-cheng/latex-action@v3
with:
working_directory:cv
root_file:monjoie_cv.tex
#Uselatexmkwithpdflatex(default)
compiler:latexmk
args:-pdf-halt-on-error-file-line-error
continue_on_error:true
pre_compile:|
tlmgrupdate--self
tlmgrinstallgeometrytabularxxcolorhyperrefsectstymathpazo

-name:Prepareoutputfolder
run:mkdir-ppublic

-name:MovePDF
run:mvcv/monjoie_cv.pdfpublic/cv.pdf

-name:Commitartifacts
uses:EndBug/add-and-commit@v9
with:
add:public/cv.pdf
message:"chore(cv):rebuildLaTeXPDF"
env:
GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
