name: build-cv

on:
  push:
    paths:
      - "cv/**"
      - ".github/workflows/cv.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF (pdflatex via latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: cv
          root_file: monjoie_cv.tex
          compiler: latexmk
          args: -pdf -halt-on-error -file-line-error
          continue_on_error: true   # so we can read the log if it fails

      - name: Show last 200 lines of log on failure
        if: failure()
        run: |
          echo "---- monjoie_cv.log (tail) ----"
          tail -n 200 cv/monjoie_cv.log || true

      - name: Prepare output folder
        run: mkdir -p public

      - name: Move PDF (fail with log if missing)
        run: |
          if [ -f cv/monjoie_cv.pdf ]; then
            mv cv/monjoie_cv.pdf public/cv.pdf
          else
            echo "::error::PDF not generated. See log above."
            exit 1
          fi

      - name: Commit artifacts
        uses: EndBug/add-and-commit@v9
        with:
          add: public/cv.pdf
          message: "chore(cv): rebuild LaTeX PDF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
